services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./Keycloak
      dockerfile: Dockerfile
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}             # Set the admin username
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}  # Set the admin password
    ports:
      - "8080:8080"
    command: ["start-dev"]

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Admin email for pgAdmin
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}       # Admin password for pgAdmin
  #   ports:
  #     - "8081:80"                             # Access pgAdmin on port 8081
  #   depends_on:
  #     - postgres

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile  # Path to your service's Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/keycloakdb  # Same URL
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REALM_NAME: ${REALM_NAME}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM_ADMIN_PASSWORD: ${KEYCLOAK_REALM_ADMIN_PASSWORD}

    ports:
      - "8082:8082"  # Expose a different port for this service

volumes:
  postgres_data:  # Named volume for persistent PostgreSQL storage
